name: ESM and IISM Builds

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: "Install dependencies"
        run: npm install

      - name: "Run Jest tests"
        run: npm test

  deploy:
    needs: test
    name: Minify JS
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Auto Minify"
        uses: nizarmah/auto-minify@v3
        with:
          directory: 'lib'
          overwrite: true

      # Auto commits minified files to the repository
      # Ignore it if you don't want to commit the files to the repository 
      - name: "Auto committing minified files"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
#          repository: 'lib'
          commit_message: "Github Action: Auto Minified JS files"
#          branch: ${{ github.ref }}
#      - name: "npm ci"
#        run: npm ci

#      - name: "Build"
#        run: npm run build

#      - name: "Linters"
#        run: npm run lint

#      - name: "Unit Tests"
#        run: npm run test

#      - name: "Artifacts"
#        uses: actions/upload-artifact@v3
#        with:
#          path: |
#            lib/sepa.js
#            lib/sepa.min.js
            
  # This workflow contains a single job called "greet"
#  greet:
    # The type of runner that the job will run on
#    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
    # Runs a single command using the runners shell
#    - name: Send greeting
#      run: echo "Hello ${{ inputs.name }}"